

export const full_name_to_abbreviation = {
    "Organisation for Economic Cooperation and Development": "OECD",
    "World Intellectual Property Organization": "WIPO",
    "United Nations": "UN",
    "International Monetary Fund": "IMF",
    "World Health Organization": "WHO",
    "World Trade Organization": "WTO",
    "European Union": "EU",
    "North Atlantic Treaty Organization": "NATO",
    "United Nations Educational, Scientific and Cultural Organization": "UNESCO",
    "United Nations International Children's Emergency Fund": "UNICEF",
    "Food and Agriculture Organization": "FAO",
    "International Labour Organization": "ILO",
    "National Aeronautics and Space Administration": "NASA",
    "Intergovernmental Panel on Climate Change": "IPCC",
    "International Civil Aviation Organization": "ICAO",
    "International Fund for Agricultural Development": "IFAD",
    "Asian Development Bank": "ADB",
    "United Nations High Commissioner for Refugees": "UNHCR",
    "General Agreement on Tariffs and Trade": "GATT",
    "International Trade Centre": "ITC",
    "Organization of the Petroleum Exporting Countries": "OPEC",
    "International Atomic Energy Agency": "IAEA",
    "United Nations Development Programme": "UNDP",
    "United Nations Population Fund": "UNFPA",
    "International Organization for Migration": "IOM",
    "International Criminal Police Organization": "INTERPOL",
    "International Organization for Standardization": "ISO",
    "International Court of Justice": "ICJ",
    "European Investment Bank": "EIB",
    "Association of Southeast Asian Nations": "ASEAN",
    "International Criminal Court": "ICC",
    "World Food Programme": "WFP",
    "United Nations Industrial Development Organization": "UNIDO",
    "Organization for Security and Co-operation in Europe": "OSCE",
    "European Organization for Nuclear Research": "CERN",
    "Environmental Protection Agency": "EPA",
    "Group of Twenty": "G20",
    "Brazil, Russia, India, China, South Africa": "BRICS",
    "Federal Bureau of Investigation": "FBI",
    "Central Intelligence Agency": "CIA",
    "United States Agency for International Development": "USAID",
    "United Nations Environment Programme": "UNEP",
    "International Finance Corporation": "IFC",
    "World Wildlife Fund": "WWF",
    "Global Alliance for Vaccines and Immunization": "GAVI",
    "European Commission": "EC",
    "United Nations Children's Fund": "UNICEF",
    "African Union": "AU",
    "World Meteorological Organization": "WMO",
    "International Maritime Organization": "IMO",
    "United Nations Office on Drugs and Crime": "UNODC",
    "European Central Bank": "ECB",
    "International Development Association": "IDA",
    "United Nations Framework Convention on Climate Change": "UNFCCC",
    "International Renewable Energy Agency": "IRENA",
    "International Telecommunication Union": "ITU",
    "World Bank Group": "WBG",
    "United Nations Human Rights Council": "UNHRC",
    "United Nations Conference on Trade and Development": "UNCTAD",
    "Economic Commission for Latin America and the Caribbean": "ECLAC",
    "International Federation of Red Cross and Red Crescent Societies": "IFRC",
    "International Union for Conservation of Nature": "IUCN",
    "International Monetary and Financial Committee": "IMFC",
    "International Monetary Cooperation Committee": "IMCC",
    "Economic and Social Commission for Asia and the Pacific": "ESCAP",
    "United Nations Commission on International Trade Law": "UNCITRAL",
    "International Institute for Sustainable Development": "IISD",
    "Global Environmental Facility": "GEF",
    "World Economic Forum": "WEF",
    "International Centre for Settlement of Investment Disputes": "ICSID",
    "World Food Programme": "WFP",
    "World Bank": "WB",
    "Organisation for the Prohibition of Chemical Weapons": "OPCW",
    "Organization of American States": "OAS",
    "International Criminal Tribunal for the former Yugoslavia": "ICTY",
    "International Criminal Tribunal for Rwanda": "ICTR",
    "Permanent Court of Arbitration": "PCA",
    "International Labour Organization": "ILO",
    "International Monetary Fund": "IMF",
    "European Court of Human Rights": "ECHR",
    "European Court of Justice": "ECJ",
    "Commonwealth of Independent States": "CIS",
    "Organization of Islamic Cooperation": "OIC",
    "Economic Community of West African States": "ECOWAS",
    "African Development Bank": "AfDB",
    "International Chamber of Commerce": "ICC",
    "North American Free Trade Agreement": "NAFTA",
    "Southern Common Market": "MERCOSUR",
    "Central American Integration System": "SICA",
    "East African Community": "EAC",
    "South Asian Association for Regional Cooperation": "SAARC",
    "Gulf Cooperation Council": "GCC",
    "International Finance Corporation": "IFC",
    "Council of Europe": "COE",
    "International Maritime Organization": "IMO",
    "United Nations Economic and Social Council": "ECOSOC",
    "International Whaling Commission": "IWC",
    "World Customs Organization": "WCO",
    "World Intellectual Property Organization": "WIPO",
    "International Seabed Authority": "ISA",
    "African Union Peace and Security Council": "AUPSC",
    "Financial Action Task Force": "FATF",
    "Joint United Nations Programme on HIV/AIDS": "UNAIDS",
    "United Nations Office for Disaster Risk Reduction": "UNDRR",
    "International Federation of Accountants": "IFAC",
    "European Union Intellectual Property Office": "EUIPO",
    "European Space Agency": "ESA",
    "International Tropical Timber Organization": "ITTO",
    "Convention on Biological Diversity": "CBD",
    "Convention on International Trade in Endangered Species of Wild Fauna and Flora": "CITES",
    "Basel Convention on the Control of Transboundary Movements of Hazardous Wastes and their Disposal": "Basel Convention",
    "International Civil Society Action Network": "ICAN",
    "Climate Action Network International": "CAN-I",
    "United Nations Convention to Combat Desertification": "UNCCD",
    "International Maritime Satellite Organization": "INMARSAT",
    "International Union of Railways": "UIC",
    "Commonwealth of Nations": "Commonwealth",
    "International Red Cross and Red Crescent Movement": "RCRC",
    "World Health Assembly": "WHA",
    "International Olympic Committee": "IOC",
    "World Anti-Doping Agency": "WADA",
    "International Paralympic Committee": "IPC",
    "Fédération Internationale de Football Association": "FIFA",
    "Union of European Football Associations": "UEFA",
    "International Rugby Board": "IRB",
    "International Cricket Council": "ICC",
    "World Trade Organization": "WTO",
    "United Nations High Commissioner for Human Rights": "UNHCHR"
}
