

export const full_name_to_abbreviation = {
        
        "organisation for economic cooperation and development": "oecd",
        "organization for economic cooperation and development": "oecd",
        "organisation for economic co-operation and development": "oecd",
        "bundesministerium für wirtschaft und energie": "bmwi",
        "world intellectual property organization": "wipo",
        "united nations": "un",
        "international monetary fund": "imf",
        "world health organization": "who",
        "world trade organization": "wto",
        "european union": "eu",
        "north atlantic treaty organization": "nato",
        "united nations educational, scientific and cultural organization": "unesco",
        "united nations international children's emergency fund": "unicef",
        "food and agriculture organization": "fao",
        "international labour organization": "ilo",
        "national aeronautics and space administration": "nasa",
        "intergovernmental panel on climate change": "ipcc",
        "international civil aviation organization": "icao",
        "international fund for agricultural development": "ifad",
        "asian development bank": "adb",
        "united nations high commissioner for refugees": "unhcr",
        "general agreement on tariffs and trade": "gatt",
        "international trade centre": "itc",
        "organization of the petroleum exporting countries": "opec",
        "international atomic energy agency": "iaea",
        "united nations development programme": "undp",
        "united nations population fund": "unfpa",
        "international organization for migration": "iom",
        "international criminal police organization": "interpol",
        "international organization for standardization": "iso",
        "international court of justice": "icj",
        "european investment bank": "eib",
        "association of southeast asian nations": "asean",
        "international criminal court": "icc",
        "world food programme": "wfp",
        "united nations industrial development organization": "unido",
        "organization for security and co-operation in europe": "osce",
        "european organization for nuclear research": "cern",
        "environmental protection agency": "epa",
        "group of twenty": "g20",
        "brazil, russia, india, china, south africa": "brics",
        "federal bureau of investigation": "fbi",
        "central intelligence agency": "cia",
        "united states agency for international development": "usaid",
        "united nations environment programme": "unep",
        "international finance corporation": "ifc",
        "world wildlife fund": "wwf",
        "global alliance for vaccines and immunization": "gavi",
        "european commission": "ec",
        "united nations children's fund": "unicef",
        "african union": "au",
        "world meteorological organization": "wmo",
        "international maritime organization": "imo",
        "united nations office on drugs and crime": "unodc",
        "european central bank": "ecb",
        "international development association": "ida",
        "united nations framework convention on climate change": "unfccc",
        "international renewable energy agency": "irena",
        "international telecommunication union": "itu",
        "world bank group": "wbg",
        "united nations human rights council": "unhrc",
        "united nations conference on trade and development": "unctad",
        "economic commission for latin america and the caribbean": "eclac",
        "international federation of red cross and red crescent societies": "ifrc",
        "international union for conservation of nature": "iucn",
        "international monetary and financial committee": "imfc",
        "economic and social commission for asia and the pacific": "escap",
        "united nations commission on international trade law": "uncitral",
        "international institute for sustainable development": "iisd",
        "global environmental facility": "gef",
        "world economic forum": "wef",
        "international centre for settlement of investment disputes": "icsid",
        "organisation for the prohibition of chemical weapons": "opcw",
        "organization of american states": "oas",
        "international criminal tribunal for the former yugoslavia": "icty",
        "international criminal tribunal for rwanda": "ictr",
        "permanent court of arbitration": "pca",
        "international labour organization": "ilo",
        "international monetary fund": "imf",
        "european court of human rights": "echr",
        "european court of justice": "ecj",
        "commonwealth of independent states": "cis",
        "organization of islamic cooperation": "oic",
        "economic community of west african states": "ecowas",
        "african development bank": "afdb",
        "international chamber of commerce": "icc",
        "north american free trade agreement": "nafta",
        "southern common market": "mercosur",
        "central american integration system": "sica",
        "east african community": "eac",
        "south asian association for regional cooperation": "saarc",
        "gulf cooperation council": "gcc",
        "council of europe": "coe",
        "international whaling commission": "iwc",
        "world customs organization": "wco",
        "international seabed authority": "isa",
        "african union peace and security council": "aupsc",
        "financial action task force": "fatf",
        "joint united nations programme on hiv/aids": "unaids",
        "united nations office for disaster risk reduction": "undrr",
        "international federation of accountants": "ifac",
        "european union intellectual property office": "euipo",
        "european space agency": "esa",
        "international tropical timber organization": "itto",
        "convention on biological diversity": "cbd",
        "convention on international trade in endangered species of wild fauna and flora": "cites",
        "international civil society action network": "ican",
        "climate action network international": "can-i",
        "united nations convention to combat desertification": "unccd",
        "international maritime satellite organization": "inmarsat",
        "international union of railways": "uic",
        "commonwealth of nations": "commonwealth",
        "international red cross and red crescent movement": "rcrc",
        "world health assembly": "wha",
        "international olympic committee": "ioc",
        "world anti-doping agency": "wada",
        "international paralympic committee": "ipc",
        "fédération internationale de football association": "fifa",
        "union of european football associations": "uefa",
        "international rugby board": "irb",
        "international cricket council": "icc",
        "united nations high commissioner for human rights": "unhchr"
    };
    